name: CI

on:
  push:
    branches:
      - main
      - feature/github-actions-ci

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::330905068651:role/git-role-aws
          aws-region: us-east-1
      
      - name: Set image tag 
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update Dockerrun image tags
        run: |
          sed -i "s/:v2/:${IMAGE_TAG}/g" Dockerrun.aws.json

      - name: Docker version
        run: docker --version     

      - name: Build client test image
        run: docker build -t react-test -f ./client/Dockerfile.dev ./client

      - name: Run client tests
        run: docker run react-test npm test -- --coverage --watchAll=false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build client image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:${IMAGE_TAG} ./client

      - name: Build nginx image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx:${IMAGE_TAG} ./nginx

      - name: Build server
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:${IMAGE_TAG} -f ./server/Dockerfile.dev ./server

      - name: Build worker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:${IMAGE_TAG} -f ./worker/Dockerfile.dev ./worker
      
      - name: Push client
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:${IMAGE_TAG}  

      - name: Push nginx
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx:${IMAGE_TAG}

      - name: Push server
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:${IMAGE_TAG}

      - name: Push worker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:${IMAGE_TAG}

      - name: Upload Dockerrun to S3
        run: |
          aws s3 cp Dockerrun.aws.json s3://complex-beanstalk-0c29dc86b1f767fc9edcfd343a/Dockerrun-${IMAGE_TAG}.aws.json